CC = gcc
CFLAGS = -Wall

# Default target
all: server client

server: server.c
	$(CC) $(CFLAGS) -pthread -o server server.c

client: client.c
	$(CC) $(CFLAGS) -o client client.c

# Mark 'clean' and 'cleanse' as phony targets
.PHONY: clean cleanse

clean:
	rm -f server client *.o

cleanse:
	rm -f server client *.o && rm -rf database
